services:
  - type: web
    name: taskmanager
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn taskmanagerproject.wsgi:application --log-file - --workers 3 --threads 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "taskmanager.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
    disk:
      name: data
      mountPath: /opt/render/project/src
    autoDeploy: true
databases:
  - name: taskmanager-db
    plan: free
name: can be anything; Render will give you a subdomain like taskmanager.onrender.com

